In [2]:
import numpy as np

In [3]:
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [5]:
a2 = np.array([[1,2.0,3.3],
              [4,5,6.5]])
a3 = np.array([[[1,2,3],
               [4,5,6],
               [3,6,4]],
               
               [[3,6,7],
               [7,3,6],
               [12,54,55]]])

In [6]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [7]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 3,  6,  4]],

       [[ 3,  6,  7],
        [ 7,  3,  6],
        [12, 54, 55]]])

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(2, 3, 3)

In [10]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [11]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [12]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [13]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [16]:
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## Create array


In [18]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [19]:
sample_array.dtype

dtype('int32')

In [21]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [22]:
ones.dtype

dtype('float64')

In [23]:
type(ones)

numpy.ndarray

In [26]:
zeroes = np.zeros((2,3))
zeroes

array([[0., 0., 0.],
       [0., 0., 0.]])

In [28]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [31]:
random_array = np.random.randint(0,10,size=(3,5))
random_array

array([[3, 7, 5, 7, 1],
       [0, 7, 8, 1, 0],
       [4, 7, 8, 6, 1]])

In [32]:
random_array.size

15

In [33]:
random_array.shape

(3, 5)

In [36]:
random_array2 = np.random.random((5,3))
random_array2

array([[0.73548584, 0.30273502, 0.36801731],
       [0.31967995, 0.46475156, 0.30257076],
       [0.91662873, 0.69357547, 0.1363548 ],
       [0.57931982, 0.08214388, 0.04812043],
       [0.18756744, 0.34779531, 0.10168   ]])

In [38]:
random_array2.shape

(5, 3)

In [40]:
random_array3 = np.random.rand(5,3)
random_array3

array([[0.28794545, 0.79477397, 0.65281717],
       [0.62518281, 0.02263911, 0.04731758],
       [0.36308425, 0.69959678, 0.77362185],
       [0.37240495, 0.09948898, 0.03977157],
       [0.93162661, 0.50048098, 0.55540791]])

In [46]:
# Pseudo random numbers
# np.random.seed()
random_array4 = np.random.randint(10,size=(5,3))
random_array4

array([[7, 1, 7],
       [5, 7, 7],
       [6, 8, 8],
       [3, 1, 2],
       [2, 6, 7]])

In [48]:
random_array4.shape

(5, 3)

In [77]:
np.random.seed(7)
random_array5 = np.random.random((5,3))
random_array5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [78]:
random_array5 = np.random.random((5,3))
random_array5

array([[0.90959353, 0.21338535, 0.45212396],
       [0.93120602, 0.02489923, 0.60054892],
       [0.9501295 , 0.23030288, 0.54848992],
       [0.90912837, 0.13316945, 0.52341258],
       [0.75040986, 0.66901324, 0.46775286]])

In [86]:
np.unique(random_array4)

array([1, 2, 3, 5, 6, 7, 8])

In [87]:
a3.shape


(2, 3, 3)

In [88]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 3,  6,  4]],

       [[ 3,  6,  7],
        [ 7,  3,  6],
        [12, 54, 55]]])

In [89]:
a3[:2,:2,:2]

array([[[1, 2],
        [4, 5]],

       [[3, 6],
        [7, 3]]])

In [91]:
a4 = np.random.randint(10, size=(2,3,4,5))
a4

array([[[[1, 1, 5, 3, 2],
         [0, 4, 8, 7, 1],
         [4, 9, 3, 6, 7],
         [1, 0, 2, 7, 0]],

        [[0, 9, 8, 2, 0],
         [5, 5, 0, 9, 0],
         [8, 4, 5, 1, 4],
         [0, 7, 2, 0, 3]],

        [[9, 8, 3, 7, 1],
         [0, 1, 4, 6, 1],
         [0, 1, 0, 1, 8],
         [4, 1, 6, 8, 5]]],


       [[[2, 4, 7, 4, 1],
         [2, 8, 5, 2, 9],
         [6, 2, 5, 7, 7],
         [5, 5, 6, 0, 6]],

        [[4, 6, 2, 6, 8],
         [7, 0, 5, 8, 9],
         [7, 7, 6, 2, 5],
         [6, 1, 9, 3, 4]],

        [[0, 3, 5, 6, 4],
         [0, 4, 1, 5, 2],
         [4, 8, 7, 5, 7],
         [5, 3, 7, 6, 2]]]])

In [92]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [93]:
 a4[:,:,:,:1]

array([[[[1],
         [0],
         [4],
         [1]],

        [[0],
         [5],
         [8],
         [0]],

        [[9],
         [0],
         [0],
         [4]]],


       [[[2],
         [2],
         [6],
         [5]],

        [[4],
         [7],
         [7],
         [6]],

        [[0],
         [0],
         [4],
         [5]]]])

## Manipulation

In [97]:
a1


array([1, 2, 3])

In [99]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [100]:
a1+ones

array([2., 3., 4.])

In [103]:
a1

array([1, 2, 3])

In [101]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [102]:
a1*a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [104]:
a1 ** 2


array([1, 4, 9])

In [105]:
 np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [106]:
np.add(a1,ones)

array([2., 3., 4.])

In [107]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])