In [1]:
import numpy as np

In [2]:
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1,2.0,3.3],
              [4,5,6.5]])
a3 = np.array([[[1,2,3],
               [4,5,6],
               [3,6,4]],
               
               [[3,6,7],
               [7,3,6],
               [12,54,55]]])

In [5]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 3,  6,  4]],

       [[ 3,  6,  7],
        [ 7,  3,  6],
        [12, 54, 55]]])

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(2, 3, 3)

In [10]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [11]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))